### ISSUE TITLE
server says: BadAuthentication

### ISSUE THREAD

**Issue by 89z** [fahadakbar24/google-play-api#1]
Using this code:

~~~py
from gpapi.googleplay import GooglePlayAPI
mail = "srpen6@gmail.com"
passwd = "PASSWORD"
api = GooglePlayAPI(locale="en_US", timezone="UTC", device_codename="hero2lte")
api.login(email=mail, password=passwd)
~~~

I get this result:

~~~
Traceback (most recent call last):
  File "D:\Desktop\google-play-api-main\play.py", line 6, in <module>
    api.login(email=mail, password=passwd)
  File "D:\Desktop\google-play-api-main\gpapi\googleplay.py", line 238, in login
    raise LoginError("server says: " + params["error"])
gpapi.googleplay.LoginError: 'server says: BadAuthentication'
~~~

**Comment by fahadakbar24** [comment]
- Enable 2 factor authentication and use the app specific password

- Also don't provide email and password for each run instead provide them for the first after which use gsfid and auth_sub_token for the consequent ones. These values are returned for every successful login i.e., for api.login(...).

**Comment by 89z** [comment]
I linked to a fix for the issue
