### ISSUE TITLE
gpapi.googleplay.LoginError: 'server says: BadAuthentication'

### ISSUE THREAD

**Issue by vadimszzz** [fahadakbar24/google-play-api#2]
```
Traceback (most recent call last):
  ....
  File "/Users/x/Downloads/Projects/********/********/cli/gp.py", line 206, in download
    download_package(**kwargs)
  File "/Users/x/Downloads/Projects/********/********/cli/gp.py", line 101, in download_package
    api.login(config['GOOGLE_LOGIN'], config['GOOGLE_PASSWORD'], config['GOOGLE_AUTH_TOKEN'])
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/gpapi/googleplay.py", line 238, in login
    raise LoginError("server says: " + params["error"])
gpapi.googleplay.LoginError: 'server says: BadAuthentication'
```

**Comment by fahadakbar24** [comment]
Please enable 2 factor auth on your google account then generate and use the app specific password.

**Comment by vadimszzz** [comment]
No thanks. I think I must use another library that works without app specific passwords
